apiVersion: v1
kind: Service
metadata:
  name: app-back
spec:
  selector:
    app: app-back
  ports:
    - name: app-back
      port: 7080
      targetPort: 7080
      nodePort: 30780
  type: NodePort
