apiVersion: v1
kind: ConfigMap
metadata:
  name: postgress-initdb-config
data:
  postgres_init.sh: |-
    #!/bin/bash
    set -e
    psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
      # Crear usuario billingapp
      CREATE USER billingapp WITH PASSWORD 'qwerty';
      # Crear base de datos billingapp_db
      CREATE DATABASE billingapp_db;
      # Otorgar privilegios a billingapp y postgres
      GRANT ALL PRIVILEGES ON DATABASE billingapp_db TO billingapp;
      GRANT ALL PRIVILEGES ON DATABASE billingapp_db TO postgres;
    EOSQL

