apiVersion: v1
kind: Service
metadata:
  name: postgress
spec:
  selector:
    app: postgress
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432
  type: LoadBalancer

